-- This script insert a common user with User authority
-- The password is '123456', which match with the hash generated by PasswordEncoderConfig to this string
INSERT INTO "user" (username, password, roles)
VALUES ('common_user', '{bcrypt}$2a$10$BDR7iWP3uGLqxuWmaiZoWOAMhMsABpTNaBpJWruAK/M7NJeYplX1q', 'USER');
